version: "3.3"
services:
  zcaseplus:
    build: ""
    ports:
      - "10.35.16.77:8501:8501"
    image:  zcaseregistry.azurecr.io/zcaseplus:2022.1.0
    restart: always
    volumes:
      - /home/petr/Projects/tests/logs/:/app/mnt/logs/
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 500M
