version: "3.3"
services:
  zcaseplus:
    build: ""
    ports:
      - "0.0.0.0:8501:8501"
    image:  zcaseplus:2022.2.0
    restart: always
    volumes:
      - /home/petr/Projects/ehh2021-challange-7/mnt/logs:/app/mnt/logs/
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 500M
